"""
    Automox Console API

    API for use with the Automox Console  # noqa: E501

    The version of the OpenAPI document: 2021-08-10
    Contact: support@automox.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.policies_api import PoliciesApi  # noqa: E501


class TestPoliciesApi(unittest.TestCase):
    """PoliciesApi unit test stubs"""

    def setUp(self):
        self.api = PoliciesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_policy(self):
        """Test case for create_policy

        Create a New Policy  # noqa: E501
        """
        pass

    def test_delete_policy(self):
        """Test case for delete_policy

        Delete Specific Policy Object  # noqa: E501
        """
        pass

    def test_execute_policy(self):
        """Test case for execute_policy

        Schedule a Policy for Immediate Remediation  # noqa: E501
        """
        pass

    def test_generate_policy_device_filter_preview(self):
        """Test case for generate_policy_device_filter_preview

        Policy Device Filters Preview  # noqa: E501
        """
        pass

    def test_get_policies(self):
        """Test case for get_policies

        List All Policy Objects  # noqa: E501
        """
        pass

    def test_get_policy(self):
        """Test case for get_policy

        List Specific Policy Object  # noqa: E501
        """
        pass

    def test_get_policy_stats(self):
        """Test case for get_policy_stats

        List Policy Compliance Stats  # noqa: E501
        """
        pass

    def test_update_policy(self):
        """Test case for update_policy

        Updates a specific policy object for the authenticated user.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
