"""
    Automox Console API

    API for use with the Automox Console  # noqa: E501

    The version of the OpenAPI document: 2021-08-10
    Contact: support@automox.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.server_detail_disks import ServerDetailDISKS


class TestServerDetailDISKS(unittest.TestCase):
    """ServerDetailDISKS unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testServerDetailDISKS(self):
        """Test ServerDetailDISKS"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ServerDetailDISKS()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
