# coding: utf-8

"""
    Automox Console API

    API for use with the Automox Console  # noqa: E501

    OpenAPI spec version: 2021-11-16
    Contact: support@automox.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import automox_console_sdk
from automox_console_sdk.models.server_with_policies_policy_status import ServerWithPoliciesPolicyStatus  # noqa: E501
from automox_console_sdk.rest import ApiException


class TestServerWithPoliciesPolicyStatus(unittest.TestCase):
    """ServerWithPoliciesPolicyStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testServerWithPoliciesPolicyStatus(self):
        """Test ServerWithPoliciesPolicyStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = automox_console_sdk.models.server_with_policies_policy_status.ServerWithPoliciesPolicyStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
