"""
    Automox Console API

    API for use with the Automox Console  # noqa: E501

    The version of the OpenAPI document: 2021-08-10
    Contact: support@automox.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.device_status_policy_statuses import DeviceStatusPolicyStatuses
globals()['DeviceStatusPolicyStatuses'] = DeviceStatusPolicyStatuses
from openapi_client.model.device_status import DeviceStatus


class TestDeviceStatus(unittest.TestCase):
    """DeviceStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeviceStatus(self):
        """Test DeviceStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DeviceStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
