"""
    Automox Console API

    API for use with the Automox Console  # noqa: E501

    The version of the OpenAPI document: 2021-08-10
    Contact: support@automox.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.policy_device_filters_output_results import PolicyDeviceFiltersOutputResults
globals()['PolicyDeviceFiltersOutputResults'] = PolicyDeviceFiltersOutputResults
from openapi_client.model.policy_device_filters_output import PolicyDeviceFiltersOutput


class TestPolicyDeviceFiltersOutput(unittest.TestCase):
    """PolicyDeviceFiltersOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPolicyDeviceFiltersOutput(self):
        """Test PolicyDeviceFiltersOutput"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PolicyDeviceFiltersOutput()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
