"""
    Automox Console API

    API for use with the Automox Console  # noqa: E501

    The version of the OpenAPI document: 2021-08-10
    Contact: support@automox.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.server_policy_status import ServerPolicyStatus


class TestServerPolicyStatus(unittest.TestCase):
    """ServerPolicyStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testServerPolicyStatus(self):
        """Test ServerPolicyStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ServerPolicyStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
