# coding: utf-8

"""
    Automox Console API

    API for use with the Automox Console  # noqa: E501

    OpenAPI spec version: 2021-10-04
    Contact: support@automox.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import automox_console_sdk
from automox_console_sdk.models.any_ofinline_response2001 import AnyOfinlineResponse2001  # noqa: E501
from automox_console_sdk.rest import ApiException


class TestAnyOfinlineResponse2001(unittest.TestCase):
    """AnyOfinlineResponse2001 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnyOfinlineResponse2001(self):
        """Test AnyOfinlineResponse2001"""
        # FIXME: construct object with mandatory attributes with example values
        # model = automox_console_sdk.models.any_ofinline_response2001.AnyOfinlineResponse2001()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
