# coding: utf-8

"""
    Automox Console API

    API for use with the Automox Console  # noqa: E501

    OpenAPI spec version: 2021-08-10
    Contact: support@automox.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import automox_console_sdk
from automox_console_sdk.models.org_endpoint_limit_data import OrgEndpointLimitData  # noqa: E501
from automox_console_sdk.rest import ApiException


class TestOrgEndpointLimitData(unittest.TestCase):
    """OrgEndpointLimitData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrgEndpointLimitData(self):
        """Test OrgEndpointLimitData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = automox_console_sdk.models.org_endpoint_limit_data.OrgEndpointLimitData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
