"""
    Automox Console API

    API for use with the Automox Console  # noqa: E501

    The version of the OpenAPI document: 2021-08-10
    Contact: support@automox.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.approvals_api import ApprovalsApi  # noqa: E501


class TestApprovalsApi(unittest.TestCase):
    """ApprovalsApi unit test stubs"""

    def setUp(self):
        self.api = ApprovalsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_update_approvals(self):
        """Test case for update_approvals

        Update a Manual Approval Record  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
