"""
    Automox Console API

    API for use with the Automox Console  # noqa: E501

    The version of the OpenAPI document: 2021-08-10
    Contact: support@automox.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.notification_sent_data import NotificationSentData


class TestNotificationSentData(unittest.TestCase):
    """NotificationSentData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNotificationSentData(self):
        """Test NotificationSentData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NotificationSentData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
