"""
    Automox Console API

    API for use with the Automox Console  # noqa: E501

    The version of the OpenAPI document: 2021-08-10
    Contact: support@automox.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.packages_api import PackagesApi  # noqa: E501


class TestPackagesApi(unittest.TestCase):
    """PackagesApi unit test stubs"""

    def setUp(self):
        self.api = PackagesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_device_packages(self):
        """Test case for get_device_packages

        List Software Packages for Specific Device  # noqa: E501
        """
        pass

    def test_get_organization_packages(self):
        """Test case for get_organization_packages

        List All Software Packages for All Devices  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
