# coding: utf-8

"""
    Automox Console API

    API for use with the Automox Console  # noqa: E501

    OpenAPI spec version: 2021-09-20
    Contact: support@automox.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ApiKey(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'name': 'str',
        'is_enabled': 'bool',
        'expires_at': 'datetime',
        'created_at': 'datetime',
        'user': 'ApiKeyUser'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'is_enabled': 'is_enabled',
        'expires_at': 'expires_at',
        'created_at': 'created_at',
        'user': 'user'
    }

    def __init__(self, id=None, name=None, is_enabled=None, expires_at=None, created_at=None, user=None):  # noqa: E501
        """ApiKey - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._is_enabled = None
        self._expires_at = None
        self._created_at = None
        self._user = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if is_enabled is not None:
            self.is_enabled = is_enabled
        if expires_at is not None:
            self.expires_at = expires_at
        if created_at is not None:
            self.created_at = created_at
        if user is not None:
            self.user = user

    @property
    def id(self):
        """Gets the id of this ApiKey.  # noqa: E501


        :return: The id of this ApiKey.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ApiKey.


        :param id: The id of this ApiKey.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this ApiKey.  # noqa: E501


        :return: The name of this ApiKey.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ApiKey.


        :param name: The name of this ApiKey.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def is_enabled(self):
        """Gets the is_enabled of this ApiKey.  # noqa: E501


        :return: The is_enabled of this ApiKey.  # noqa: E501
        :rtype: bool
        """
        return self._is_enabled

    @is_enabled.setter
    def is_enabled(self, is_enabled):
        """Sets the is_enabled of this ApiKey.


        :param is_enabled: The is_enabled of this ApiKey.  # noqa: E501
        :type: bool
        """

        self._is_enabled = is_enabled

    @property
    def expires_at(self):
        """Gets the expires_at of this ApiKey.  # noqa: E501


        :return: The expires_at of this ApiKey.  # noqa: E501
        :rtype: datetime
        """
        return self._expires_at

    @expires_at.setter
    def expires_at(self, expires_at):
        """Sets the expires_at of this ApiKey.


        :param expires_at: The expires_at of this ApiKey.  # noqa: E501
        :type: datetime
        """

        self._expires_at = expires_at

    @property
    def created_at(self):
        """Gets the created_at of this ApiKey.  # noqa: E501


        :return: The created_at of this ApiKey.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this ApiKey.


        :param created_at: The created_at of this ApiKey.  # noqa: E501
        :type: datetime
        """

        self._created_at = created_at

    @property
    def user(self):
        """Gets the user of this ApiKey.  # noqa: E501


        :return: The user of this ApiKey.  # noqa: E501
        :rtype: ApiKeyUser
        """
        return self._user

    @user.setter
    def user(self, user):
        """Sets the user of this ApiKey.


        :param user: The user of this ApiKey.  # noqa: E501
        :type: ApiKeyUser
        """

        self._user = user

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApiKey, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiKey):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
