# coding: utf-8

"""
    Automox Console API

    API for use with the Automox Console  # noqa: E501

    OpenAPI spec version: 2021-09-20
    Contact: support@automox.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PolicyDeviceFiltersPreview(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'device_filters': 'list[DeviceFiltersInner]',
        'server_groups': 'list[int]'
    }

    attribute_map = {
        'device_filters': 'device_filters',
        'server_groups': 'server_groups'
    }

    def __init__(self, device_filters=None, server_groups=None):  # noqa: E501
        """PolicyDeviceFiltersPreview - a model defined in Swagger"""  # noqa: E501
        self._device_filters = None
        self._server_groups = None
        self.discriminator = None
        if device_filters is not None:
            self.device_filters = device_filters
        if server_groups is not None:
            self.server_groups = server_groups

    @property
    def device_filters(self):
        """Gets the device_filters of this PolicyDeviceFiltersPreview.  # noqa: E501


        :return: The device_filters of this PolicyDeviceFiltersPreview.  # noqa: E501
        :rtype: list[DeviceFiltersInner]
        """
        return self._device_filters

    @device_filters.setter
    def device_filters(self, device_filters):
        """Sets the device_filters of this PolicyDeviceFiltersPreview.


        :param device_filters: The device_filters of this PolicyDeviceFiltersPreview.  # noqa: E501
        :type: list[DeviceFiltersInner]
        """

        self._device_filters = device_filters

    @property
    def server_groups(self):
        """Gets the server_groups of this PolicyDeviceFiltersPreview.  # noqa: E501


        :return: The server_groups of this PolicyDeviceFiltersPreview.  # noqa: E501
        :rtype: list[int]
        """
        return self._server_groups

    @server_groups.setter
    def server_groups(self, server_groups):
        """Sets the server_groups of this PolicyDeviceFiltersPreview.


        :param server_groups: The server_groups of this PolicyDeviceFiltersPreview.  # noqa: E501
        :type: list[int]
        """

        self._server_groups = server_groups

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PolicyDeviceFiltersPreview, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PolicyDeviceFiltersPreview):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
