# coding: utf-8

"""
    Automox Console API

    API for use with the Automox Console  # noqa: E501

    OpenAPI spec version: 2021-09-20
    Contact: support@automox.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ServerPolicyStatus(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'organization_id': 'int',
        'policy_id': 'int',
        'server_id': 'int',
        'policy_name': 'str',
        'policy_type_name': 'str',
        'status': 'int',
        'result': 'str',
        'create_time': 'str',
        'next_remediation': 'datetime'
    }

    attribute_map = {
        'id': 'id',
        'organization_id': 'organization_id',
        'policy_id': 'policy_id',
        'server_id': 'server_id',
        'policy_name': 'policy_name',
        'policy_type_name': 'policy_type_name',
        'status': 'status',
        'result': 'result',
        'create_time': 'create_time',
        'next_remediation': 'next_remediation'
    }

    def __init__(self, id=None, organization_id=None, policy_id=None, server_id=None, policy_name=None, policy_type_name=None, status=None, result=None, create_time=None, next_remediation=None):  # noqa: E501
        """ServerPolicyStatus - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._organization_id = None
        self._policy_id = None
        self._server_id = None
        self._policy_name = None
        self._policy_type_name = None
        self._status = None
        self._result = None
        self._create_time = None
        self._next_remediation = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if organization_id is not None:
            self.organization_id = organization_id
        if policy_id is not None:
            self.policy_id = policy_id
        if server_id is not None:
            self.server_id = server_id
        if policy_name is not None:
            self.policy_name = policy_name
        if policy_type_name is not None:
            self.policy_type_name = policy_type_name
        if status is not None:
            self.status = status
        if result is not None:
            self.result = result
        if create_time is not None:
            self.create_time = create_time
        if next_remediation is not None:
            self.next_remediation = next_remediation

    @property
    def id(self):
        """Gets the id of this ServerPolicyStatus.  # noqa: E501


        :return: The id of this ServerPolicyStatus.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ServerPolicyStatus.


        :param id: The id of this ServerPolicyStatus.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def organization_id(self):
        """Gets the organization_id of this ServerPolicyStatus.  # noqa: E501


        :return: The organization_id of this ServerPolicyStatus.  # noqa: E501
        :rtype: int
        """
        return self._organization_id

    @organization_id.setter
    def organization_id(self, organization_id):
        """Sets the organization_id of this ServerPolicyStatus.


        :param organization_id: The organization_id of this ServerPolicyStatus.  # noqa: E501
        :type: int
        """

        self._organization_id = organization_id

    @property
    def policy_id(self):
        """Gets the policy_id of this ServerPolicyStatus.  # noqa: E501


        :return: The policy_id of this ServerPolicyStatus.  # noqa: E501
        :rtype: int
        """
        return self._policy_id

    @policy_id.setter
    def policy_id(self, policy_id):
        """Sets the policy_id of this ServerPolicyStatus.


        :param policy_id: The policy_id of this ServerPolicyStatus.  # noqa: E501
        :type: int
        """

        self._policy_id = policy_id

    @property
    def server_id(self):
        """Gets the server_id of this ServerPolicyStatus.  # noqa: E501


        :return: The server_id of this ServerPolicyStatus.  # noqa: E501
        :rtype: int
        """
        return self._server_id

    @server_id.setter
    def server_id(self, server_id):
        """Sets the server_id of this ServerPolicyStatus.


        :param server_id: The server_id of this ServerPolicyStatus.  # noqa: E501
        :type: int
        """

        self._server_id = server_id

    @property
    def policy_name(self):
        """Gets the policy_name of this ServerPolicyStatus.  # noqa: E501


        :return: The policy_name of this ServerPolicyStatus.  # noqa: E501
        :rtype: str
        """
        return self._policy_name

    @policy_name.setter
    def policy_name(self, policy_name):
        """Sets the policy_name of this ServerPolicyStatus.


        :param policy_name: The policy_name of this ServerPolicyStatus.  # noqa: E501
        :type: str
        """

        self._policy_name = policy_name

    @property
    def policy_type_name(self):
        """Gets the policy_type_name of this ServerPolicyStatus.  # noqa: E501


        :return: The policy_type_name of this ServerPolicyStatus.  # noqa: E501
        :rtype: str
        """
        return self._policy_type_name

    @policy_type_name.setter
    def policy_type_name(self, policy_type_name):
        """Sets the policy_type_name of this ServerPolicyStatus.


        :param policy_type_name: The policy_type_name of this ServerPolicyStatus.  # noqa: E501
        :type: str
        """
        allowed_values = ["patch", "custom", "required_software"]  # noqa: E501
        if policy_type_name not in allowed_values:
            raise ValueError(
                "Invalid value for `policy_type_name` ({0}), must be one of {1}"  # noqa: E501
                .format(policy_type_name, allowed_values)
            )

        self._policy_type_name = policy_type_name

    @property
    def status(self):
        """Gets the status of this ServerPolicyStatus.  # noqa: E501


        :return: The status of this ServerPolicyStatus.  # noqa: E501
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this ServerPolicyStatus.


        :param status: The status of this ServerPolicyStatus.  # noqa: E501
        :type: int
        """

        self._status = status

    @property
    def result(self):
        """Gets the result of this ServerPolicyStatus.  # noqa: E501


        :return: The result of this ServerPolicyStatus.  # noqa: E501
        :rtype: str
        """
        return self._result

    @result.setter
    def result(self, result):
        """Sets the result of this ServerPolicyStatus.


        :param result: The result of this ServerPolicyStatus.  # noqa: E501
        :type: str
        """

        self._result = result

    @property
    def create_time(self):
        """Gets the create_time of this ServerPolicyStatus.  # noqa: E501


        :return: The create_time of this ServerPolicyStatus.  # noqa: E501
        :rtype: str
        """
        return self._create_time

    @create_time.setter
    def create_time(self, create_time):
        """Sets the create_time of this ServerPolicyStatus.


        :param create_time: The create_time of this ServerPolicyStatus.  # noqa: E501
        :type: str
        """

        self._create_time = create_time

    @property
    def next_remediation(self):
        """Gets the next_remediation of this ServerPolicyStatus.  # noqa: E501


        :return: The next_remediation of this ServerPolicyStatus.  # noqa: E501
        :rtype: datetime
        """
        return self._next_remediation

    @next_remediation.setter
    def next_remediation(self, next_remediation):
        """Sets the next_remediation of this ServerPolicyStatus.


        :param next_remediation: The next_remediation of this ServerPolicyStatus.  # noqa: E501
        :type: datetime
        """

        self._next_remediation = next_remediation

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ServerPolicyStatus, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ServerPolicyStatus):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
