# coding: utf-8

"""
    Automox Console API

    API for use with the Automox Console  # noqa: E501

    OpenAPI spec version: 2021-09-20
    Contact: support@automox.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class WsusConfig(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'server_group_id': 'int',
        'is_managed': 'bool',
        'server_url': 'str',
        'created_at': 'str',
        'updated_at': 'str'
    }

    attribute_map = {
        'id': 'id',
        'server_group_id': 'server_group_id',
        'is_managed': 'is_managed',
        'server_url': 'server_url',
        'created_at': 'created_at',
        'updated_at': 'updated_at'
    }

    def __init__(self, id=None, server_group_id=None, is_managed=None, server_url=None, created_at=None, updated_at=None):  # noqa: E501
        """WsusConfig - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._server_group_id = None
        self._is_managed = None
        self._server_url = None
        self._created_at = None
        self._updated_at = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if server_group_id is not None:
            self.server_group_id = server_group_id
        if is_managed is not None:
            self.is_managed = is_managed
        if server_url is not None:
            self.server_url = server_url
        if created_at is not None:
            self.created_at = created_at
        if updated_at is not None:
            self.updated_at = updated_at

    @property
    def id(self):
        """Gets the id of this WsusConfig.  # noqa: E501


        :return: The id of this WsusConfig.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this WsusConfig.


        :param id: The id of this WsusConfig.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def server_group_id(self):
        """Gets the server_group_id of this WsusConfig.  # noqa: E501


        :return: The server_group_id of this WsusConfig.  # noqa: E501
        :rtype: int
        """
        return self._server_group_id

    @server_group_id.setter
    def server_group_id(self, server_group_id):
        """Sets the server_group_id of this WsusConfig.


        :param server_group_id: The server_group_id of this WsusConfig.  # noqa: E501
        :type: int
        """

        self._server_group_id = server_group_id

    @property
    def is_managed(self):
        """Gets the is_managed of this WsusConfig.  # noqa: E501


        :return: The is_managed of this WsusConfig.  # noqa: E501
        :rtype: bool
        """
        return self._is_managed

    @is_managed.setter
    def is_managed(self, is_managed):
        """Sets the is_managed of this WsusConfig.


        :param is_managed: The is_managed of this WsusConfig.  # noqa: E501
        :type: bool
        """

        self._is_managed = is_managed

    @property
    def server_url(self):
        """Gets the server_url of this WsusConfig.  # noqa: E501


        :return: The server_url of this WsusConfig.  # noqa: E501
        :rtype: str
        """
        return self._server_url

    @server_url.setter
    def server_url(self, server_url):
        """Sets the server_url of this WsusConfig.


        :param server_url: The server_url of this WsusConfig.  # noqa: E501
        :type: str
        """

        self._server_url = server_url

    @property
    def created_at(self):
        """Gets the created_at of this WsusConfig.  # noqa: E501


        :return: The created_at of this WsusConfig.  # noqa: E501
        :rtype: str
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this WsusConfig.


        :param created_at: The created_at of this WsusConfig.  # noqa: E501
        :type: str
        """

        self._created_at = created_at

    @property
    def updated_at(self):
        """Gets the updated_at of this WsusConfig.  # noqa: E501


        :return: The updated_at of this WsusConfig.  # noqa: E501
        :rtype: str
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this WsusConfig.


        :param updated_at: The updated_at of this WsusConfig.  # noqa: E501
        :type: str
        """

        self._updated_at = updated_at

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(WsusConfig, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WsusConfig):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
