name: Continuous Integration

on:
  pull_request:
  workflow_dispatch:

jobs:
  run_tests:
    name: Run tests
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: 3.9

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip coverage
      - name: Install Tox
        run: pip install tox tox-gh-actions
      - name: Run Tox
        run: tox
