name: Client Generation

on:
  pull_request:
  workflow_dispatch:

jobs:
  validate:
    name: Validate Automox Console OpenAPI Spec
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Validate OpenAPI definition
        uses: char0n/swagger-editor-validate@v1.2.1
        with:
          definition-file: specs/ax_console.yaml

  generate:
    name: Generate from OpenAPI Spec and Commit
    runs-on: ubuntu-latest
    needs: [validate]
    env:
      JAVA_VERSION: 1.11
      SWAGGER_CODEGEN_VERSION: 3.0.29

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - name: Download Swagger Codegen CLI ${{ env.SWAGGER_CODEGEN_VERSION }}
        run: |
          wget https://repo1.maven.org/maven2/io/swagger/codegen/v3/swagger-codegen-cli/${{ env.SWAGGER_CODEGEN_VERSION }}/swagger-codegen-cli-${{ env.SWAGGER_CODEGEN_VERSION }}.jar -O generation/swagger-codegen-cli.jar
      - name: Generate Client
        run: |
          java -jar generation/swagger-codegen-cli.jar generate -i specs/ax_console.yaml -l python -c generation/config.json -o ./
      - name: Get project version
        id: get_project_version
        run: echo ::set-output name=VERSION::$(jq -r '.packageVersion' generation/config.json)
      - name: Update setup.py Version
        run: |
          sed -i 's/VERSION = ".*"/VERSION = "${{ steps.get_project_version.outputs.VERSION }}"/' setup.py
      - name: Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated changes from swagger codegen generation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
