name: Continuous Integration

on:
  pull_request:

jobs:
  validate:
    name: Validate Automox Console OpenAPI Spec
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Validate OpenAPI definition
        uses: char0n/swagger-editor-validate@v1.2.1
        with:
          definition-file: specs/ax_console.yaml

  generate:
    name: Generate Client
    runs-on: ubuntu-latest
    needs: [validate]
    env:
      JAVA_VERSION: 1.11
      SWAGGER_CODEGEN_VERSION: 3.0.27

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - name: Download Swagger Codegen CLI ${{ env.SWAGGER_CODEGEN_VERSION }}
        run: |
          wget https://repo1.maven.org/maven2/io/swagger/codegen/v3/swagger-codegen-cli/${{ env.SWAGGER_CODEGEN_VERSION }}/swagger-codegen-cli-${{ env.SWAGGER_CODEGEN_VERSION }}.jar -O generation/swagger-codegen-cli.jar
      - name: Generate Client
        run: |
          java -jar generation/swagger-codegen-cli.jar generate -i specs/ax_console.yaml -l python -c generation/config.json -o ./

  run_tests:
    name: Run tests
    runs-on: ubuntu-latest
    needs: [validate, generate]
    env:
      PYTHON_VERSION: 3.9

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip coverage
      - name: Install Tox
        run: pip install tox tox-gh-actions
      - name: Run Tox
        run: tox

  commit_changes:
    name: Commit changes
    runs-on: ubuntu-latest
    needs: [generate, run_tests]

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated changes from swagger codegen generation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
