name: Release

on:
  push:
    tags:
    - "v*.*.*"

jobs:
  release:

    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: 3.9

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install Dependencies
        run: |
          python3 -m pip install --user --upgrade setuptools wheel twine
      - name: Create Package
        run: |
          rm -rf dist/
          python3 setup.py sdist bdist_wheel
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            specs/ax_console.yaml
            dist/*
#      - name: Publish
#        env:
#          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
#          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
#        run: |
#          python3 -m twine upload dist/*